use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :smartcitydogs, SmartCityDogsWeb.Endpoint,
       http: [port: 4000],
       https: [
         port: 4443,
         otp_app: :smartcitydogs,
         keyfile: "priv/keys/localhost.key",
         certfile: "priv/keys/localhost.cert"
       ],
       debug_errors: true,
       code_reloader: true,
       check_origin: false,
       watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :smartcitydogs, SmartCityDogs.Repo,
       adapter: Ecto.Adapters.Postgres,
       username: System.get_env("DB_USER"),
       password: System.get_env("DB_PASSWORD"),
       database: System.get_env("DB_NAME"),
       hostname: System.get_env("DB_HOST"),
       pool_size: 10

config :ueberauth, Ueberauth,
       providers: [
         facebook: {Ueberauth.Strategy.Facebook, [profile_fields: "name,email,first_name,last_name"]},
       ]

config :ueberauth, Ueberauth.Strategy.Facebook.OAuth,
       client_id: System.get_env("FACEBOOK_ID"),
       client_secret: System.get_env("FACEBOOK_SECRET")
